name: CI-CD

on:
  push:
    branches: [main, dev]
    paths:
      - web/**
  pull_request:
    branches: [main, dev]
    paths:
      - web/**

jobs:
  BUILD_IMAGE:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: List content
        run: ls -a
